{'Beauchamps, Charles': {'Total': 223.0},
 'Briois, Sebastien': {'Total': 195.0},
 'Burthey, Kirkland': {'Total': 200.0},
 'Cohn, Jonathan': {'Total': 140.0},
 'Conte, Matthieu': {'Total': 211.0},
 'El Mrani, Aicha': {'Total': 282.5},
 'Ganko, Eric': {'Total': 223.0},
 'Graham, Steve': {'Total': 205.5},
 'Green, Julie': {'Total': 168.0},
 'Kavanaugh, Laura': {'Total': 183.5},
 'Leysens, Maurice': {'Total': 200.0},
 'Moughamer, Todd': {'Total': 207.0},
 'Muller, Cedric': {'Total': 288.25},
 'NCGR': {'Total': 0.0},
 'NGOU, KISSI': {'Total': 96.0},
 'Nebion': {'Total': 0.0},
 'Not Allocated': {'Total': 0},
 'Parvathaneni, Usha': {'Total': 207.5},
 'Rose, Mark': {'Total': 178.0},
 'Sharma, Pranav': {'Total': 200.0},
 'Tiberi, Guillaume': {'Total': 157.0},
 'Whalen, Brian': {'Total': 222.0}}